### ISSUE TITLE
Allow movable guild frame

### ISSUE THREAD

**Issue by Rezy942** [nezroy/DeModal#28] opened 2023-05-03 14:36 UTC
As title - please do this because it sucks to have it ALL THE WAY TO THE LEFT on a super widescreen monitor.
Please... !!!!

**Comment by jayseeem** [comment] 2023-05-21 19:34
`The "Guild & Communities" window being movable broke as of 10.0.0. Support for moving this panel has been disabled until I can determine the cause.`

https://github.com/nezroy/DeModal#known-issues

**Closed** 2023-05-24 12:22 UTC
