### ISSUE TITLE
Certain window positions reset between character sessions

### ISSUE THREAD

**Issue by sebid** [nezroy/DeModal#13] opened 2022-06-21 08:35 UTC
Hello!
I really like the addon and as a user I have a gripe about certain windows not saving positions in between sessions.

I am unsure if it's Elvui or some of my other addons that can overwrite these states (Overachiever, TSM, etc.). I experimented with all addons disabled and only DeModal enabled, positions were still resetting.

Currently, I'm seeing the following windows not saving in the position I put them after a relog:
- AchievementFrame
- EncounterJournal
- CalendarFrame
- FlightMapFrame
- WorldMapFrame
- Quest Log (Part of WorldMapFrame?)
- GarrisonLandingPage
- GarrisonBuildingFrame
- GarrisonRecruiterFrame
- GarrisonMissionFrame
- GarrisonShipyardFrame
- GarrisonCapacitiveDisplayFrame
- OrderHallTalentFrame - Order Advancement / Cypher Console / Box of Many Things
- OrderHallMissionFrame
- ArtifactFrame
- ScrappingMachineFrame
- IslandQueueFrame
- BFAMissionFrame
- AzeriteEssenceUI
- SoulbindViewer
- CovenantRenownFrame
- AnimaDiversionFrame
- CovenantSanctumFrame
- CovenantMissionFrame
- RuneforgeFrame
- CommunitiesFrame - Guild & Communities
- GuildBankFrame
- TabardFrame
- GuildRegistrarFrame
- WardrobeFrame
- InspectFrame
- ItemUpgradeFrame
- ItemSocketingFrame
- WeeklyRewardsFrame - Great Vault
- AuctionHouseFrame
- PetStableFrame
- CollectionsJournal
- PlayerTalentsFrame
- TradeSkillFrame
- ClassTrainerFrame
- VoidStorageFrame
... and possibly others I have not checked.

**Comment by nezroy** [comment] 2022-10-29 09:29
Resolved by (duplicate of) #6

**Closed by nezroy** 2022-10-29 09:29 UTC
